config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"
  get "/gifts" => "gifts#new", as: :new_gift
  post "/gifts" => "gifts#create", as: :create_gift

  resources :events, only: [:show, :update, :destroy, :new, :create, :edit]
  resources :recipients

end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :age,numericality: {greater_than: 0}
  validates :budget , numericality: {greater_than_or_equal_to: 0}, allow_nil: true

end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :authenticate_user!
  def recipient_params
    params.require(:recipient).permit(:name,:age,:occupation,:hobbies,:likes,:dislikes,:budget)
  end

  def show
    id=params[:id]
    @recipient=current_user.recipients.find(id)
  end

  def index
    @recipients=current_user.recipients.order(created_at: :desc)
  end

  def new
    @recipient=current_user.recipients.build
  end

  def create
    @recipient=Recipient.new(recipient_params)
    @recipient.user=current_user

    if @recipient.save
      flash[:notice]="#{@recipient.name} was successfully created."
      redirect_to recipients_path
    else
      flash[:warning]="enter valid characteristics"#temporary for first sprint
      redirect_to recipients_path
    end
  end

  def edit
    @recipient=current_user.recipients.find(params[:id])
  end

  def update
    @recipient=current_user.recipients.find(params[:id])
    if @recipient.update(recipient_params)
      flash[:notice]="#{@recipient.name} was successfully updated."
      redirect_to recipients_path
    else
      flash[:warning]="enter valid characteristics"#temporary for first sprint
      redirect_to recipients_path
    end
  end

  def destroy
    @recipient=current_user.recipients.find(params[:id])
    @recipient.destroy
    flash[:notice]="#{@recipient.name} was removed."
    redirect_to recipient_path
  end

end

app/views/recipients/edit.html.erb
<h1>Edit recipient</h1>
<%= form_for @recipient do |recipient|  %>
  <p>
    <%=recipient.label :name %>
    <%=recipient.text_field :name%>
  </p>
  <p>
    <%=recipient.label :age %>
    <%=recipient.text_field :age%>
  </p>
  <p>
    <%=recipient.label :occupation %>
    <%=recipient.text_field :occupation%>
  </p>
  <p>
    <%=recipient.label :hobbies %>
    <%=recipient.text_field :hobbies%>
  </p>
  <p>
    <%=recipient.label :likes %>
    <%=recipient.text_field :likes%>
  </p>
  <p>
    <%=recipient.label :dislikes %>
    <%=recipient.text_field :dislikes%>
  </p>
  <p>
    <%=recipient.label :budget %>
    <%=recipient.text_field :budget%>
  </p>
  <p><%=recipient.submit "submit" %></p>
<% end %>

<%= link_to "Back",recipients_path %>

app/views/recipients/index.html.erb
<h1>Recipients</h1>
<p>
  <%= link_to "Add new Recipient",new_recipient_path %>
</p>
<ul>
  <% @recipients.each do |recipient| %>
    <li>
      <strong> <%=recipient.name %></strong>
      (<%=recipient.age %> years old)
      <%= link_to "Edit",edit_recipient_path(recipient) %>
    </li>
  <% end %>
</ul>
<%= link_to "back", home_index_path %>
<% if @recipients.empty? %>
  <p>You do not have any recipients.</p>
<% end %>

app/views/recipients/new.html.erb
<h1>New Recipient</h1>
<%= form_for @recipient do |recipient| %>
  <p>
    <%= recipient.label :name%><br>
    <%=recipient.text_field :name %>
  </p>
  <p>
    <%= recipient.label :age%><br>
    <%=recipient.text_field :age %>
  </p>
  <p>
    <%= recipient.label :occupation%><br>
    <%=recipient.text_field :occupation %>
  </p>
  <p>
    <%= recipient.label :hobbies%><br>
    <%=recipient.text_area :hobbies %>
  </p>
  <p>
    <%= recipient.label :likes%><br>
    <%=recipient.text_area :likes %>
  </p>
  <p>
    <%= recipient.label :dislikes%><br>
    <%=recipient.text_area :dislikes %>
  </p>
  <p>
    <%= recipient.label :budget%><br>
    <%=recipient.number_field :budget %>
  </p>

  <p><%= recipient.submit "Create" %></p>
<% end %>

<p><%= link_to "Back to recipients", recipients_path %></p>