config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"
  get "/gifts" => "gifts#new", as: :new_gift
  post "/gifts" => "gifts#create", as: :create_gift

  resources :events, only: [:show, :update, :destroy, :new, :create, :edit]
  resources :recipients

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gifts = Gift.all
    @username = current_user.email
    @username = @username[0,@username.index('@')]
    @events = Event.all.order(date: :desc)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome, <%=@username %>.</h1>
<%= button_to "Sign Out", destroy_user_session_path, method: :delete %>

<h2>Your purchased gifts</h2>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
  </tr>
  </thead>
  <tbody>
  <% @gifts.each do |gift| %>
    <tr>
      <td><%= gift.name %></td>
      <td><%= gift.description %></td>
      <td><%= gift.price %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "Create a new gift", :new_gift %>
<br>
<h2>All Events</h2>
<table id="events">
  <thead>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Theme</th>
    <th>Date</th>
    <th>More info</th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.location %></td>
      <td><%= event.theme %></td>
      <td><%= event.date %></td>
      <td><%= link_to "More about #{event.title}", event_path(event) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Add new event', new_event_path %>

<h2>Your Recipients</h2>
<p>
  <%= link_to "view your recipients",recipients_path %>
  <%= link_to "add a new recipient", new_recipient_path %>
</p>