config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"
  get "/gifts" => "gifts#new", as: :new_gift
  post "/gifts" => "gifts#create", as: :create_gift

  resources :events, only: [:show, :update, :destroy, :new, :create, :edit]
  resources :recipients

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :gifts

  validates :user, presence: true

  scope :for_user, ->(user) { where(user: user) }
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController

  before_action :authenticate_user!

  def event_params
    params.require(:event).permit(:title, :location, :description, :date, :start_time, :theme)
  end

  def show
    @event = Event.for_user(current_user).find_by(:id => params[:id])
    if @event == nil
      flash[:notice] = "Event not found"
      redirect_to home_index_path
    end
  end

  def new
    # default: render 'new' template
  end

  def create
    @event = Event.create!(event_params.merge(:user_id => current_user.id))
    flash[:notice] = "#{@event.title} was successfully created."
    redirect_to home_index_path
  end

  #def edit
  #  @event = Event.find params[:id]
  #end

  def update
    @event = Event.for_user(current_user).find_by(:id => params[:id])
    if @event == nil
      flash[:notice] = "Event not found"
      redirect_to home_index_path
    end
    @event.update_attributes!(event_params)
    flash[:notice] = "#{@event.title} was successfully updated."
    redirect_to events_path(@event)
  end

  def destroy
    @event = Event.for_user(current_user).find_by(:id => params[:id])
    if @event == nil
      flash[:notice] = "Event not found"
      redirect_to home_index_path
    end
    @event.destroy
    flash[:notice] = "Event '#{@event.title}' deleted."
    redirect_to home_index_path
  end
end

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
<main>
  <h1>Create New Event</h1>

  <%= form_tag events_path do %>

    <%= label :event, :title, 'Title' %>
    <%= text_field :event, 'title', :required => true%>

    <%= label :event, :location, 'Location' %>
    <%= text_field :event, 'location' %>

    <%= label :event, :theme, 'Theme' %>
    <%= text_field :event, 'theme' %>

    <%= label :event, :description, 'Description' %>
    <%= text_field :event, 'description' %>

    <%= label :event, :date, 'Event Date' %>
    <%= date_select :event, :date, :required => true%>

    <%= label :event, :start_time, 'Start Time' %>
    <%= time_field :event, :start_time %>
    <br>
    <%= submit_tag 'Create Event' %>

  <% end %>
</main>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<main>
  <%# in app/views/events/show.html.haml %>

  <h2>Details about <%= @event.title %></h2>

  <ul id="details">
    <li>
      <% if @event.date %>
        Date:
        <%= @event.date.strftime("%B %d, %Y") %>
      <%end %>
    </li>
    <li>
      Location:
      <%= @event.location %>
    </li>
    <li>
      Theme:
      <%= @event.theme %>
    </li>
  </ul>

  <h3>Description:</h3>

  <p id="description"><%= @event.description %></p>

  <%#= link_to 'Edit', edit_event_path(@event) %>
  <%= button_to 'Delete', event_path(@event), method: :delete, confirm: 'Are you sure?' %>
  <%= link_to 'Back to home', home_index_path %>
</main>
</html>